#!/usr/bin/bash

rm -r ./output
mkdir ./output

############## WEB CRAWLER ##############
cd WebCrawler/submit
echo "inside $(pwd)"

./runner-script input.txt in out

############## PAGE RANK ###############
cd ../../PageRank/MapReduce
echo "inside $(pwd)"

./runner-script /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar 2 			../../WebCrawler/submit/output/finall
# 				STREAMING JAR														ITERATIONS	INPUT DIR

############## FINAL OUTPUT ############
cp ./output/* ../../output/